name: nnyy
description: "TV app"
publish_to: 'Kinwai'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  html: ^0.15.4
  icon_decoration: ^2.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  universal_html: ^2.2.4
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.8
  webviewx_plus: ^0.5.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis: ^13.2.0
  google_sign_in_web: ^0.12.4+2
  google_sign_in_dartio: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
